global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Trading API
  - job_name: 'trading-api'
    static_configs:
      - targets: ['trading-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Trading Engine
  - job_name: 'trading-engine'
    static_configs:
      - targets: ['trading-engine:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Trading Worker
  - job_name: 'trading-worker'
    static_configs:
      - targets: ['trading-worker:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
